### ISSUE TITLE
Add `AG1` graph template

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/biomarker-catalog#12]
To do:

- [x] Migrate internal `AG1` page to here from devel BAC
- [x] Make sure no internal packages or data are used and remove those if present
  - [x] `ggplot2.utils` is ok to use, as we are in the process of publishing this anyway - let's see if it already works now while it is not on CRAN yet
- [x] Change the formatting similarly as in TLGC:
    - [x] use tab sets
    - [x] shorter title and longer subtitle
    - [x] session info
	- [x] Compare output: https://insightsengineering.github.io/tlg-catalog/graphs/other/ippg01.html
	- [x] With input: https://github.com/insightsengineering/tlg-catalog/blob/main/graphs/other/ippg01.qmd
- [x] Test compilation locally
    - [x] Make sure to run `staged.dependencies` to update dependencies (incl. `tern` package etc.)
    - [x] Check if anything is broken e.g. due to package updates

**Comment by danielinteractive** [comment]
@moronip81 this could be a good next issue

**Comment by danielinteractive** [comment]
Thanks @moronip81 , can you please push the branch to origin, and create a draft PR? Then it is much easier to help.

My guess is that we need to adapt the `AG1` code accordingly to the deprecation warning. Can you try that?

**Comment by moronip81** [comment]
@danielinteractive draft PR created, so that you can see the warning rendered... I agree that adapting the code according to the warning should help
