### ISSUE TITLE
[Question]: Is teal.devel needed in `staged.dependencies.yaml`?

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/biomarker-catalog#45]
### What is your question?

Is this unsupported package needed in staged.dependencies.yaml?

https://github.com/insightsengineering/biomarker-catalog/blob/main/staged_dependencies.yaml#L17

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by pawelru** [comment]
Most likely not. This is not used in the catalog at all: https://github.com/search?q=repo%3Ainsightsengineering%2Fbiomarker-catalog%20teal.devel&type=code

I would say it's a part of https://github.com/insightsengineering/nestdevs-tasks/issues/34 and can be closed here

**Comment by m7pr** [comment]
Closing this, let's followup on https://github.com/insightsengineering/nestdevs-tasks/issues/34
