### ISSUE TITLE
Teal module screenshots only show session ID and nothing else

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/biomarker-catalog#47]
Problem:
<img width="1268" alt="image" src="https://github.com/insightsengineering/biomarker-catalog/assets/1071227/80c39bff-0b3b-41f3-8510-7bbc3feeffe6">

Is this something known @gogonzo ?

**Comment by danielinteractive** [comment]
Actually in TLGC seems the same problem exists:

<img width="1334" alt="image" src="https://github.com/insightsengineering/biomarker-catalog/assets/1071227/3e533fcb-0ff5-4b57-a8e2-b3e5760647b5">

@insightsengineering/idr fyi

**Comment by danielinteractive** [comment]
Did you have the chance to look at this already @cicdguy ?

**Comment by gogonzo** [comment]
@danielinteractive thanks for this. Last time I've checked tlg-catalog against main everything was fine. I'll check again. Do you confirm the same problem locally?

**Comment by danielinteractive** [comment]
@gogonzo I didn't try locally, but this is still today the situation on TLG catalog, and also Biomarker Catalog (see screenshot above)

**Comment by donyunardi** [comment]
Looking at the error message here:
https://insightsengineering.github.io/biomarker-catalog/graphs/rnag01.html

<img src="https://github.com/insightsengineering/biomarker-catalog/assets/8597300/d728f924-4a1e-445d-a91e-e5476651e201" width="70%" height="70%" />

It's using `teal` from `main` branch, @cicdguy can you confirm?
If so, then we need to fix this to always pull from last stable release.

**Comment by danielinteractive** [comment]
Are we sure this is not a different problem? E.g. on internal BAC we now have 60 seconds and this problem still persists.

**Comment by danielinteractive** [comment]
@cicdguy does the new solution work?

**Comment by danielinteractive** [comment]
fixed on devel via #52 - thanks @cicdguy
