### ISSUE TITLE
Update KM plots after `g_km` refactor

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/biomarker-catalog#56]
Update KM plots following `g_km` refactor in `tern` (https://github.com/insightsengineering/tern/pull/1210)

**Comment by danielinteractive** [comment]
Hi @edelarua I now see
<img width="666" alt="image" src="https://github.com/insightsengineering/biomarker-catalog/assets/1071227/7a715350-e67d-4b6a-a6b8-eb39847b10e0">
in
https://github.com/insightsengineering/biomarker-catalog/actions/runs/8570682159/job/23489132408

**Comment by edelarua** [comment]
> Hi @edelarua I now see 

@danielinteractive I see. Probably best to just revert all of the updates until after `tern` is released to CRAN (which should happen soon). Since there are arguments that were added/deprecated in `g_km` only one of the stable or development versions will be able to produce output that looks correct/produces no warnings & errors. We probably want that to be the stable version so I will revert all of the changes for now and can reinstate at a later date.
