### ISSUE TITLE
`kg01b` rendering fails 

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/biomarker-catalog#58]
```
Quitting from lines 30-41 [unnamed-chunk-3] (kg01b.qmd)
Error in `UseMethod()`:
! no applicable method for 'ggplot_build' applied to an object of class "c('gTree', 'grob', 'gDesc')"
Backtrace:
 1. base::rbind(...)
 3. ggplot2::ggplotGrob(res1)
 7. ggplot2::ggplot_build(x)
Execution halted
```

please see https://github.com/insightsengineering/biomarker-catalog/actions/runs/8393286264/job/22987921179

**Comment by danielinteractive** [comment]
@edelarua not sure if this is related to your recent #57 ?

**Comment by edelarua** [comment]
@danielinteractive since the stable version is still failing, I will just revert the section causing the failure for now (will show a deprecation warning on the development version) and then make the update after the next release of tern on CRAN.

**Comment by danielinteractive** [comment]
sounds good, thanks @edelarua
