### ISSUE TITLE
[Bug]: summarize_vars() deprecated, replaced with analyze_vars()

### ISSUE THREAD

**Issue by jeffreyCarlLong** [insightsengineering/biomarker-catalog#69]
### What happened?

This was an issue across a couple repos. The original issue got closed with the fixes in {tern.mmrm}. Here is the original issue: [https://github.com/insightsengineering/biomarker-catalog/issues/65](https://github.com/insightsengineering/biomarker-catalog/issues/65).

This issue closes with PR: [https://github.com/insightsengineering/biomarker-catalog/pull/68](https://github.com/insightsengineering/biomarker-catalog/pull/68). 

Review is required.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by shajoezhu** [comment]
closed by #69
